# Generated by Django 5.2.6 on 2026-06-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspiciousactivity',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
