# Generated by Django 5.2.6 on 2025-10-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_message_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='attachment',
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_audio',
            field=models.FileField(blank=True, null=True, upload_to='attachments/audio/'),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_doc',
            field=models.FileField(blank=True, null=True, upload_to='attachments/docs/'),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_photo',
            field=models.ImageField(blank=True, null=True, upload_to='attachments/photos/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
