# Generated by Django 5.2.6 on 2026-07-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_summary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisummary',
            name='title',
            field=models.CharField(default='Daily AI Briefing', max_length=200),
            preserve_default=False,
        ),
    ]
