# Generated by Django 5.2.6 on 2026-07-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_role',
            field=models.CharField(choices=[('all', 'All'), ('commander', 'Commander'), ('officer', 'Officer'), ('soldier', 'Soldier')], default='all', max_length=20),
        ),
    ]
